### PR TITLE
GUI configuration

### PR DESCRIPTION
**Pull request by beqabeqa473**
Add gui
Add config spec
Replace urllib with http.client

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks. I'm going to cherry-pick parts of this, as it's a pretty big refactor, it's all in one commit and it's unclear why we need parts of it. It'd be great if you could submit unrelated changes in separate pull requests in future.

I did consider using http.client instead of urllib, but I don't think it provides any benefit. On the flip side, it requires you to split the host and port, and it doesn't pass the POST request correctly in the case that there are multiple servers running on the same port. We could fix that, but I don't think there's much point. That said, if you can explain why you prefer http.client, I'd be happy to consider it.

**Comment by beqabeqa473** [comment]
Hello.

That was a point why i replaced urllib with http.client to easily
split host and port.

On my system it is sending post request correctly.
Could you tell me what is wrong with requests? maybe i didn't test carefully.

I just didn't want to mess with concatenations and wanted to give a
flexible controll to user. Yes, we could save fully qualified url but
i thought this way would be better

On 12/3/23, James Teh ***@***.***> wrote:
> Thanks. I'm going to cherry-pick parts of this, as it's a pretty big
> refactor, it's all in one commit and it's unclear why we need parts of it.
> It'd be great if you could submit unrelated changes in separate pull
> requests in future.
>
> I did consider using http.client instead of urllib, but I don't think it
> provides any benefit. On the flip side, it requires you to split the host
> and port, and it doesn't pass the POST request correctly in the case that
> there are multiple servers running on the same port. We could fix that, but
> I don't think there's much point. That said, if you can explain why you
> prefer http.client, I'd be happy to consider it.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/jcsteh/nvda-llamaCpp/pull/2#issuecomment-1837254270
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
As for commits, yes, sorry for that. I quickly made some refactorings, and unfortunately wasn't able to commit changes in time.

**Comment by jcsteh** [comment]
> On my system it is sending post request correctly. Could you tell me what is wrong with requests?

It's possible (and common) to run a single http server on a single port which serves multiple domains. In that case, the request needs to pass the correct host. It's not enough to just pass the path.

That said, it occurs to me now that someone is probably very unlikely to host llama.cpp behind a real web server or something like that. They're more likely to host it on its own port. So, maybe it is simpler to configure the host and port separately as you suggest.

**Comment by jcsteh** [comment]
@ndarilek, in your use case, would you be hosting this behind another web server app (so the domain matters) or just on a different port on the GPU host?

**Comment by beqabeqa473** [comment]
i also thought to host it behind webserver, and i would host it if it was not so slow on my cpu

**Comment by ndarilek** [comment]
I would host this on one of our GPU nodes directly. In that instance, giving a direct URL to the API root is what I'd expect to do, whether via GUI or config. This would not be a separate server sharing space with other apps, but a VM instance with direct GPU access and only provisioned for the purpose of running a containerized server for this extension.

**Comment by jcsteh** [comment]
The reason I ask is whether there should be separate fields for host and port or just a URL. Personally, I'd prefer a URL, but I can see arguments on both sides. On one hand, llama.cpp takes a --port argument, so users might find it easier to think in terms of host and port. On the other hand, if you end up hosting this behind another web server, a URL makes more sense.

**Comment by jcsteh** [comment]
I ended up making the URL configurable rather than host and port separately. I also didn't include the timeout in the dialog, since I don't think users should really have to tweak this.

Thanks!

**Pull request closed without merging**
